import type { Topic } from "../../types";

export const mongodbInsertOneTopic: Topic = {
  id: "mongodb-insert-one",
  title: "MongoDB insertOne()",
  category: "Create & Read",
  shortExplanation: `\`collection.insertOne(doc)\` inserts a single new document into a collection.

- If \`doc\` has no \`_id\` field, MongoDB **auto-generates** one (a unique ObjectId on a real server; a simple auto-incrementing id in this sandbox) before storing it
- If \`doc\` already has an \`_id\`, that exact value is used instead — and it must be unique within the collection, or the insert fails
- The result is an **acknowledgment object**: \`{ acknowledged: true, insertedId: ... }\`, confirming the write happened and reporting exactly which id ended up on the stored document`,
  longExplanation: `\`insertOne()\` is the simplest write operation in MongoDB — you hand it one document, and it stores exactly that document as a new record in the collection. The interesting behavior isn't really in what you pass in; it's in what comes back out, and in the one field MongoDB is willing to fill in on your behalf.

- Call it as \`db.users.insertOne({ name: "Ada Lovelace", age: 28 })\`. Whatever fields you include become the stored document's fields, verbatim — MongoDB doesn't reshape, validate types, or fill in defaults for anything you didn't ask for (unless schema validation is explicitly configured, covered in its own topic later).
- Every document in a MongoDB collection needs an \`_id\` field that's unique within that collection — it's the document's primary key. If the document you pass to \`insertOne()\` doesn't include one, MongoDB doesn't leave it out or error — it silently generates one for you before the document is stored. On a real server that generated value is an **ObjectId**; this sandbox's simplified \`Collection\` uses a plain auto-incrementing number instead, since the point being taught (*some* unique id gets assigned automatically) is identical either way.
- If you *do* supply your own \`_id\` — \`insertOne({ _id: "sku-12345", name: "Widget" })\` — MongoDB uses that value exactly as given and does not touch it. This is common whenever a natural unique key already exists: a product SKU, a username, a UUID generated by another system. The only rule is that it must be unique within the collection; two documents can never share an \`_id\`.
- Inserting a document whose \`_id\` already exists elsewhere in the collection is a hard failure, not a silent overwrite — MongoDB (and the \`Collection\` class below) rejects the write with a duplicate-key error, and nothing is stored. This is worth internalizing early: \`insertOne()\` can never accidentally clobber an existing document, because a collision is an error, not an update. Updating an existing document on purpose is a different, deliberate operation (\`updateOne()\`/\`replaceOne()\`, covered elsewhere in this subject).
- The return value is small but meaningful: \`{ acknowledged: true, insertedId: <id> }\`. \`acknowledged\` reflects whether the server confirmed the write was durably applied (it's essentially always \`true\` unless you've deliberately configured a weaker write concern, a production/replica-set concept outside this sandbox's scope) — \`insertedId\` is the practically useful part, telling you exactly which id — generated or supplied — the new document ended up with. This matters constantly in real application code: you almost always need that id immediately afterward, to redirect a user to "their" new record, to link a second document to this one, or simply to confirm what got created.
- A subtle gotcha for anyone used to SQL's auto-increment primary keys: there's no gap-free, sequential counter behind a real MongoDB ObjectId the way there often is with a SQL \`SERIAL\`/\`AUTO_INCREMENT\` column. Two ObjectIds inserted moments apart are *not* "id 41" and "id 42" — they're two independently generated 12-byte values that happen to sort in roughly chronological order (the full mechanics are covered in the ObjectId topic). Don't write application logic that assumes consecutive integers unless you're deliberately supplying your own sequential \`_id\`.

Because \`insertOne()\` only ever creates exactly one document and never modifies an existing one, it's the tool you reach for the moment you have a single new record ready to persist — a new user signing up, a single new order being placed, one new blog post being published. Adding several documents at once, all in one call, is \`insertMany()\` — covered next.`,
  examples: [
    {
      id: "insert-one-auto-generated-id",
      title: "insertOne() auto-generates an _id",
      summary: "A genuine Collection.insertOne() assigning an id when none is supplied.",
      code: `class Collection {
  constructor() {
    this.docs = [];
    this.nextId = 1;
  }
  insertOne(doc) {
    if (doc._id !== undefined) {
      const exists = this.docs.some((d) => d._id === doc._id);
      if (exists) {
        throw new Error("E11000 duplicate key error: _id " + doc._id + " already exists");
      }
      this.docs.push({ ...doc });
      return { acknowledged: true, insertedId: doc._id };
    }
    const generatedId = this.nextId++;
    const withId = { _id: generatedId, ...doc };
    this.docs.push(withId);
    return { acknowledged: true, insertedId: generatedId };
  }
}

function App() {
  const [collection] = useState(() => new Collection());

  const result = collection.insertOne({ name: "Ada Lovelace", age: 28 });

  return (
    <div style={{ display: "grid", gap: 8 }}>
      <p>insertOne({"{"} name: "Ada Lovelace", age: 28 {"}"}) returned:</p>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 12, borderRadius: 6 }}>
        {JSON.stringify(result, null, 2)}
      </pre>
      <p>Stored document (note the auto-assigned _id):</p>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 12, borderRadius: 6 }}>
        {JSON.stringify(collection.docs, null, 2)}
      </pre>
    </div>
  );
}

render(<App />);`,
    },
    {
      id: "insert-one-custom-id",
      title: "Supplying your own _id",
      summary: "A custom _id is used as-is — no auto-generation happens.",
      code: `class Collection {
  constructor() {
    this.docs = [];
    this.nextId = 1;
  }
  insertOne(doc) {
    if (doc._id !== undefined) {
      const exists = this.docs.some((d) => d._id === doc._id);
      if (exists) {
        throw new Error("E11000 duplicate key error: _id " + doc._id + " already exists");
      }
      this.docs.push({ ...doc });
      return { acknowledged: true, insertedId: doc._id };
    }
    const generatedId = this.nextId++;
    const withId = { _id: generatedId, ...doc };
    this.docs.push(withId);
    return { acknowledged: true, insertedId: generatedId };
  }
}

function App() {
  const [collection] = useState(() => new Collection());

  const withCustomId = collection.insertOne({ _id: "sku-12345", name: "Widget", price: 9.99 });
  const withAutoId = collection.insertOne({ name: "Gadget", price: 19.99 });

  return (
    <div style={{ display: "grid", gap: 10 }}>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 10, borderRadius: 6 }}>
        {"insertOne({ _id: 'sku-12345', ... }) -> " + JSON.stringify(withCustomId)}
      </pre>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 10, borderRadius: 6 }}>
        {"insertOne({ name: 'Gadget', ... }) -> " + JSON.stringify(withAutoId)}
      </pre>
      <p style={{ color: "#6b7280", fontSize: 13 }}>
        The Widget keeps the id you gave it; the Gadget gets one generated for it.
      </p>
    </div>
  );
}

render(<App />);`,
    },
    {
      id: "insert-one-duplicate-id-rejected",
      title: "A duplicate _id is rejected, not overwritten",
      summary: "insertOne() never silently clobbers an existing document — a collision throws.",
      code: `class Collection {
  constructor() {
    this.docs = [];
    this.nextId = 1;
  }
  insertOne(doc) {
    if (doc._id !== undefined) {
      const exists = this.docs.some((d) => d._id === doc._id);
      if (exists) {
        throw new Error("E11000 duplicate key error: _id " + doc._id + " already exists");
      }
      this.docs.push({ ...doc });
      return { acknowledged: true, insertedId: doc._id };
    }
    const generatedId = this.nextId++;
    const withId = { _id: generatedId, ...doc };
    this.docs.push(withId);
    return { acknowledged: true, insertedId: generatedId };
  }
}

function App() {
  const [collection] = useState(() => {
    const c = new Collection();
    c.insertOne({ _id: "sku-12345", name: "Widget" });
    return c;
  });
  const [message, setMessage] = useState("Click to try inserting a second document with the same _id.");

  function tryDuplicateInsert() {
    try {
      collection.insertOne({ _id: "sku-12345", name: "Imposter Widget" });
      setMessage("No error — this should not happen!");
    } catch (err) {
      setMessage("Error thrown: " + err.message);
    }
  }

  return (
    <div style={{ display: "grid", gap: 8 }}>
      <button onClick={tryDuplicateInsert}>insertOne({"{"} _id: "sku-12345", ... {"}"}) again</button>
      <p style={{ color: "#dc2626" }}>{message}</p>
      <p>Collection still has just the original document:</p>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 10, borderRadius: 6 }}>
        {JSON.stringify(collection.docs, null, 2)}
      </pre>
    </div>
  );
}

render(<App />);`,
    },
    {
      id: "insert-one-sequence",
      title: "The insertedId is the id to hold onto afterward",
      summary: "Real code almost always needs insertedId right away — e.g. to link a second document to the first.",
      code: `class Collection {
  constructor() {
    this.docs = [];
    this.nextId = 1;
  }
  insertOne(doc) {
    if (doc._id !== undefined) {
      const exists = this.docs.some((d) => d._id === doc._id);
      if (exists) {
        throw new Error("E11000 duplicate key error: _id " + doc._id + " already exists");
      }
      this.docs.push({ ...doc });
      return { acknowledged: true, insertedId: doc._id };
    }
    const generatedId = this.nextId++;
    const withId = { _id: generatedId, ...doc };
    this.docs.push(withId);
    return { acknowledged: true, insertedId: generatedId };
  }
}

function App() {
  const [state] = useState(() => {
    const posts = new Collection();
    const comments = new Collection();

    const postResult = posts.insertOne({ title: "Hello MongoDB", body: "My first post." });
    // Use the freshly-returned insertedId to link a new document to it.
    const commentResult = comments.insertOne({
      postId: postResult.insertedId,
      text: "Great post!",
    });

    return { posts: posts.docs, comments: comments.docs, postResult, commentResult };
  });

  return (
    <div style={{ display: "grid", gap: 8 }}>
      <p>New post -> insertedId: {String(state.postResult.insertedId)}</p>
      <p>New comment links back via postId: {String(state.commentResult ? state.comments[0].postId : "")}</p>
      <pre style={{ background: "#111827", color: "#d1fae5", padding: 12, borderRadius: 6 }}>
        {JSON.stringify({ posts: state.posts, comments: state.comments }, null, 2)}
      </pre>
    </div>
  );
}

render(<App />);`,
    },
  ],
};
