import type { Topic } from "../../types";

export const cssPseudoElementsTopic: Topic = {
  id: "css-pseudo-elements",
  title: "CSS Pseudo-Elements",
  category: "CSS Layout & Positioning",
  shortExplanation: `A pseudo-element targets a **specific part** of an element's content — not the whole thing — written with a **double colon**. It can even create a brand-new box that didn't exist in the HTML at all.

- \`::before\` / \`::after\` — inserts generated content immediately inside the element, before/after its real content (requires a \`content\` value, even if empty: \`content: ""\`)
- \`::first-line\` — targets just the first rendered line of a text block
- \`::first-letter\` — targets just the first character, the basis of a classic "drop cap" effect
- \`::selection\` — styles the text a user has currently highlighted/selected`,
  longExplanation: `Pseudo-elements look similar to pseudo-classes but do something categorically different: rather than matching an element based on a *state* or *position*, a pseudo-element lets a style target *part* of an element's content, or even generate an entirely new box that has no corresponding tag anywhere in the actual HTML/JSX. The modern convention writes them with a double colon (\`::before\`) specifically to visually distinguish them from pseudo-classes (\`:hover\`), although older CSS accepted a single colon for the original four pseudo-elements for backward compatibility.

**\`::before\`** and **\`::after\`** are the most powerful and most commonly used pseudo-elements: they insert a generated inline box immediately before or after an element's actual content, positioned *inside* the element itself (as its first or last child, effectively) rather than outside it. Critically, **neither does anything without a \`content\` property** — even \`content: ""\` (an empty string) is required to make the generated box appear at all; omitting \`content\` entirely means no box is created, full stop. Once present, that generated box can be styled like any other element — given a background, size, position, transform, and so on — which is what makes \`::before\`/\`::after\` the standard technique for purely decorative additions that shouldn't clutter the actual markup: a small colored bullet before a list item, a corner ribbon on a card, an underline that animates in on hover, or (as covered in the Float topic) the invisible clearing element at the heart of a clearfix. Because they're generated by CSS rather than written in HTML, they're invisible to some accessibility tools and to anything that reads the raw DOM structure — which is exactly why they should be used only for decoration, never for content a user actually needs to read or interact with.

**\`::first-line\`** matches only the first *rendered* line of a block of text — not a fixed number of characters, but however much text actually fits on the first visual line, which means it dynamically changes if the container is resized or the font changes. It's commonly used for a subtle emphasis effect at the start of a paragraph or article, such as rendering the opening line in a slightly larger size or a different weight, purely through CSS with no need to wrap that text in its own separate tag.

**\`::first-letter\`** targets only the very first character of a block's text content, and it's the mechanism behind the traditional **drop cap** effect seen at the start of chapters in printed books and long-form articles: a dramatically enlarged, often differently-styled first letter that the rest of the paragraph's text wraps around. This works by combining a large \`font-size\` with \`float: left\` on the \`::first-letter\` pseudo-element, so the oversized letter behaves like a floated image with the following text flowing around it, exactly as covered in the Float topic.

**\`::selection\`** styles the portion of text a user has currently highlighted with their mouse or keyboard (the same text that would be copied with Ctrl/Cmd+C). Only a small subset of properties can be changed here — mainly \`color\`, \`background-color\`, and a couple of others — for the same practical reason \`:visited\` link styling is limited: giving pages full control over selection appearance could be used in ways that actively hurt usability (imagine a page making selected text invisible). Within that limited set, though, \`::selection\` is a nice small branding touch, letting a site's highlight color match its own palette instead of the browser's default blue.

A useful way to hold pseudo-elements and pseudo-classes apart conceptually: pseudo-*classes* answer "when/where is this element in a certain condition," while pseudo-*elements* answer "which specific *piece* of this element (or which entirely new, generated piece) should this rule apply to."`,
  examples: [
    {
      id: "before-after-generated-content",
      title: "::before and ::after generate content that isn't in the HTML",
      summary: "A quote mark and a corner ribbon are both created purely by CSS, with no extra markup.",
      code: `function PseudoElStyles() {
  return (
    <style>{\`
      .quote { position: relative; padding: 16px 20px; background: #f3f4f6; border-radius: 6px; }
      .quote::before { content: "\\201C"; font-size: 40px; color: #9ca3af; position: absolute; top: -6px; left: 6px; }
      .ribbon { position: relative; display: inline-block; padding: 20px; background: #dbeafe; border-radius: 6px; }
      .ribbon::after { content: "NEW"; position: absolute; top: 6px; right: -22px; transform: rotate(30deg); background: #dc2626; color: white; font-size: 10px; font-weight: 700; padding: 2px 24px; }
    \`}</style>
  );
}

function App() {
  return (
    <div style={{ display: "flex", gap: 24, flexWrap: "wrap" }}>
      <PseudoElStyles />
      <p className="quote" style={{ margin: 0, paddingLeft: 40 }}>
        A quotation mark inserted purely with ::before, not typed into the text itself.
      </p>
      <div className="ribbon">Card content</div>
    </div>
  );
}

render(<App />);`,
    },
    {
      id: "first-letter-drop-cap",
      title: "::first-letter creates a classic drop cap",
      summary: "The opening letter of the paragraph is enlarged and floated, exactly like a printed book chapter.",
      code: `function PseudoElStyles() {
  return (
    <style>{\`
      .drop-cap-demo::first-letter {
        font-size: 48px;
        font-weight: 700;
        float: left;
        line-height: 0.8;
        margin-right: 6px;
        color: #7c3aed;
      }
    \`}</style>
  );
}

function App() {
  return (
    <p className="drop-cap-demo" style={{ maxWidth: 320 }}>
      <PseudoElStyles />
      Once upon a time, a single oversized letter set the tone for an entire chapter,
      with the rest of this paragraph's text wrapping neatly around it.
    </p>
  );
}

render(<App />);`,
    },
    {
      id: "first-line-emphasis",
      title: "::first-line styles only the first rendered line",
      summary: "Only the text that visually fits on the first line is bold and colored — resize-dependent, not character-counted.",
      code: `function PseudoElStyles() {
  return (
    <style>{\`
      .first-line-demo::first-line {
        font-weight: 700;
        color: #0f766e;
      }
    \`}</style>
  );
}

function App() {
  return (
    <p className="first-line-demo" style={{ maxWidth: 260 }}>
      <PseudoElStyles />
      Only the words that actually fit on this first visual line are bold and teal —
      the rest of this paragraph continues in normal weight and color, and the exact
      cutoff point shifts automatically if the container gets narrower.
    </p>
  );
}

render(<App />);`,
    },
    {
      id: "custom-selection-color",
      title: "::selection changes the highlight color of selected text",
      summary: "Select (highlight) this paragraph's text to see a custom pink highlight instead of the browser default.",
      code: `function PseudoElStyles() {
  return (
    <style>{\`
      .custom-selection::selection {
        background: #f472b6;
        color: white;
      }
    \`}</style>
  );
}

function App() {
  return (
    <p className="custom-selection">
      <PseudoElStyles />
      Try selecting (click and drag across) this sentence — the highlight color comes
      from a real ::selection rule instead of the browser's default blue.
    </p>
  );
}

render(<App />);`,
    },
  ],
};
